import { PrismaClient } from "@prisma/client";

console.log(process.env.DATABASE_URL);
import dotenv from "dotenv";

dotenv.config();
const prisma = new PrismaClient();

async function main() {
  // const count = await prisma.vehicleDashboardData.count();
  // if (count === 0) {
  //   await prisma.vehicleDashboardData.createMany({
  //     data: [
  //       {
  //         totalEnergyConsumed: 250.0,
  //         averageSoC: 85.2,
  //         connectorType: "Type 2",
  //         totalChargingSessions: 30,
  //         averageChargingRate: 9.3,
  //         usageAverageDailyKmDriven: 50,
  //         temperatureLow: -5,
  //         temperatureHigh: 30,
  //         socRangeMin: 80,
  //         socRangeMax: 90,
  //         rangeObservedMin: 150,
  //         rangeObservedMax: 200,
  //         realRangeObserved: 180,
  //         epaProvidedRange: 220,
  //         batteryHealthSoH: 95.7,
  //         estimatedDegradation: 4.3,
  //         batteryChemistry: "Lithium-ion",
  //         endOfLife: new Date("2030-06-15"),
  //         remainingUsefulLife: 800,
  //       },
  //       {
  //         totalEnergyConsumed: 300.0,
  //         averageSoC: 78.5,
  //         connectorType: "CCS Combo",
  //         totalChargingSessions: 25,
  //         averageChargingRate: 11.2,
  //         usageAverageDailyKmDriven: 65,
  //         temperatureLow: -3,
  //         temperatureHigh: 32,
  //         socRangeMin: 75,
  //         socRangeMax: 85,
  //         rangeObservedMin: 180,
  //         rangeObservedMax: 220,
  //         realRangeObserved: 200,
  //         epaProvidedRange: 250,
  //         batteryHealthSoH: 93.8,
  //         estimatedDegradation: 6.2,
  //         batteryChemistry: "NMC",
  //         endOfLife: new Date("2031-04-20"),
  //         remainingUsefulLife: 750,
  //       },
  //       {
  //         totalEnergyConsumed: 280.0,
  //         averageSoC: 80.9,
  //         connectorType: "CHAdeMO",
  //         totalChargingSessions: 28,
  //         averageChargingRate: 10.5,
  //         usageAverageDailyKmDriven: 55,
  //         temperatureLow: 0,
  //         temperatureHigh: 28,
  //         socRangeMin: 78,
  //         socRangeMax: 88,
  //         rangeObservedMin: 160,
  //         rangeObservedMax: 210,
  //         realRangeObserved: 190,
  //         epaProvidedRange: 230,
  //         batteryHealthSoH: 94.5,
  //         estimatedDegradation: 5.5,
  //         batteryChemistry: "LFP",
  //         endOfLife: new Date("2030-12-10"),
  //         remainingUsefulLife: 780,
  //       },
  //       {
  //         totalEnergyConsumed: 320.0,
  //         averageSoC: 75.3,
  //         connectorType: "Type 1",
  //         totalChargingSessions: 24,
  //         averageChargingRate: 13.3,
  //         usageAverageDailyKmDriven: 70,
  //         temperatureLow: -2,
  //         temperatureHigh: 35,
  //         socRangeMin: 70,
  //         socRangeMax: 80,
  //         rangeObservedMin: 190,
  //         rangeObservedMax: 230,
  //         realRangeObserved: 210,
  //         epaProvidedRange: 260,
  //         batteryHealthSoH: 92.6,
  //         estimatedDegradation: 7.4,
  //         batteryChemistry: "NCA",
  //         endOfLife: new Date("2031-07-25"),
  //         remainingUsefulLife: 720,
  //       },
  //       {
  //         totalEnergyConsumed: 270.0,
  //         averageSoC: 82.6,
  //         connectorType: "Tesla Supercharger",
  //         totalChargingSessions: 27,
  //         averageChargingRate: 10.0,
  //         usageAverageDailyKmDriven: 60,
  //         temperatureLow: -1,
  //         temperatureHigh: 29,
  //         socRangeMin: 75,
  //         socRangeMax: 85,
  //         rangeObservedMin: 170,
  //         rangeObservedMax: 220,
  //         realRangeObserved: 200,
  //         epaProvidedRange: 240,
  //         batteryHealthSoH: 95.0,
  //         estimatedDegradation: 5.0,
  //         batteryChemistry: "NMC",
  //         endOfLife: new Date("2030-11-18"),
  //         remainingUsefulLife: 790,
  //       },
  //       {
  //         totalEnergyConsumed: 290.0,
  //         averageSoC: 84.3,
  //         connectorType: "Type 2",
  //         totalChargingSessions: 26,
  //         averageChargingRate: 12.1,
  //         usageAverageDailyKmDriven: 58,
  //         temperatureLow: -4,
  //         temperatureHigh: 31,
  //         socRangeMin: 77,
  //         socRangeMax: 87,
  //         rangeObservedMin: 165,
  //         rangeObservedMax: 215,
  //         realRangeObserved: 195,
  //         epaProvidedRange: 230,
  //         batteryHealthSoH: 94.3,
  //         estimatedDegradation: 5.7,
  //         batteryChemistry: "Lithium-ion",
  //         endOfLife: new Date("2030-09-22"),
  //         remainingUsefulLife: 770,
  //       },
  //       {
  //         totalEnergyConsumed: 310.0,
  //         averageSoC: 77.8,
  //         connectorType: "CCS Combo",
  //         totalChargingSessions: 29,
  //         averageChargingRate: 9.8,
  //         usageAverageDailyKmDriven: 63,
  //         temperatureLow: -3,
  //         temperatureHigh: 33,
  //         socRangeMin: 72,
  //         socRangeMax: 82,
  //         rangeObservedMin: 185,
  //         rangeObservedMax: 225,
  //         realRangeObserved: 205,
  //         epaProvidedRange: 250,
  //         batteryHealthSoH: 93.0,
  //         estimatedDegradation: 7.0,
  //         batteryChemistry: "NMC",
  //         endOfLife: new Date("2031-05-12"),
  //         remainingUsefulLife: 740,
  //       },
  //       {
  //         totalEnergyConsumed: 280.0,
  //         averageSoC: 79.4,
  //         connectorType: "CHAdeMO",
  //         totalChargingSessions: 22,
  //         averageChargingRate: 10.9,
  //         usageAverageDailyKmDriven: 56,
  //         temperatureLow: 1,
  //         temperatureHigh: 27,
  //         socRangeMin: 76,
  //         socRangeMax: 86,
  //         rangeObservedMin: 155,
  //         rangeObservedMax: 205,
  //         realRangeObserved: 185,
  //         epaProvidedRange: 240,
  //         batteryHealthSoH: 93.5,
  //         estimatedDegradation: 6.5,
  //         batteryChemistry: "LFP",
  //         endOfLife: new Date("2030-10-05"),
  //         remainingUsefulLife: 760,
  //       },
  //       {
  //         totalEnergyConsumed: 330.0,
  //         averageSoC: 73.6,
  //         connectorType: "Type 1",
  //         totalChargingSessions: 31,
  //         averageChargingRate: 12.7,
  //         usageAverageDailyKmDriven: 68,
  //         temperatureLow: -5,
  //         temperatureHigh: 36,
  //         socRangeMin: 68,
  //         socRangeMax: 78,
  //         rangeObservedMin: 195,
  //         rangeObservedMax: 235,
  //         realRangeObserved: 215,
  //         epaProvidedRange: 270,
  //         batteryHealthSoH: 91.8,
  //         estimatedDegradation: 8.2,
  //         batteryChemistry: "NCA",
  //         endOfLife: new Date("2031-08-30"),
  //         remainingUsefulLife: 710,
  //       },
  //       {
  //         totalEnergyConsumed: 290.0,
  //         averageSoC: 81.2,
  //         connectorType: "Tesla Supercharger",
  //         totalChargingSessions: 28,
  //         averageChargingRate: 10.5,
  //         usageAverageDailyKmDriven: 62,
  //         temperatureLow: -2,
  //         temperatureHigh: 30,
  //         socRangeMin: 73,
  //         socRangeMax: 83,
  //         rangeObservedMin: 175,
  //         rangeObservedMax: 225,
  //         realRangeObserved: 205,
  //         epaProvidedRange: 250,
  //         batteryHealthSoH: 94.8,
  //         estimatedDegradation: 5.2,
  //         batteryChemistry: "NMC",
  //         endOfLife: new Date("2030-12-01"),
  //         remainingUsefulLife: 780,
  //       },
  //     ],
  //   });
  // }
  // else{
  //   console.log("data already present");
  // }
}

main()
  .then(() => {
    console.log("Seed data successfully added.");
  })
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
