export const chargerTypes = [
  {
    evConnectorType: "SAE J1772 (Type 1)",
    outputCurrentType: "AC (Alternate Current)",
    supplyInput: "120 Volts or 208/240 Volts (Single-phase only)",
    maximumOutputCurrent: "16 Amps (120 Volts) 80 Amps (208/240 Volts)",
    maximumOutputPower: "1.92 kW (120 Volts) 19.2 kW (208/240 Volts)",
    evChargingLevels: "Level 1, Level 2",
    primaryCountries: "USA, Canada, Japan",
  },
  {
    evConnectorType: "Mennekes (Type 2)",
    outputCurrentType: "AC (Alternate Current)",
    supplyInput: "230 Volts (Single-Phase) or 400 Volts (three-phase)",
    maximumOutputCurrent: "32 Amps (230 Volts) 32 Amps (400 Volts)",
    maximumOutputPower: "7.6 kW (230 Volts) 22 kW (400 Volts)",
    evChargingLevels: "Level 2",
    primaryCountries: "Europe, United Kingdom, Middle East, Africa, Australia",
  },
  {
    evConnectorType: "CCS 1",
    outputCurrentType: "DC (Direct Current)",
    supplyInput: "480 Volts (three-phase)",
    maximumOutputCurrent: "500 Amps",
    maximumOutputPower: "360 kW",
    evChargingLevels: "Level 3 (DC fast charging)",
    primaryCountries: "USA, Canada, South Korea",
    "Maximum Output Voltage": "1000 Volts DC",
  },
  {
    evConnectorType: "CHAdeMO",
    outputCurrentType: "DC (Direct Current)",
    supplyInput: "400 Volts (three-phase)",
    maximumOutputCurrent: "400 Amps",
    maximumOutputPower: "400 kW",
    evChargingLevels: "Level 3 (DC fast charging)",
    primaryCountries: "Japan (older model EVs in use globally)",
  },
  {
    evConnectorType: "CHAdeMO",
    outputCurrentType: "DC (Direct Current)",
    supplyInput: "400 Volts (three-phase)",
    maximumOutputCurrent: "400 Amps",
    maximumOutputPower: "400 kW",
    evChargingLevels: "Level 3 (DC fast charging)",
    primaryCountries: "Japan (older model EVs in use globally)",
  },
  {
    evConnectorType: "CCS 2",
    outputCurrentType: "DC (Direct Current)",
    supplyInput: "400 Volts (three-phase)",
    maximumOutputCurrent: "500 Amps",
    maximumOutputPower: "360 kW",
    evChargingLevels: "Level 3 (DC fast charging)",
    primaryCountries: "Europe, United Kingdom, Middle East, Africa, Australia",
    "Maximum Output Voltage": "1000 Volts DC",
  },
  {
    evConnectorType: "GB/T (AC)",
    outputCurrentType: "AC (Alternate Current)",
    supplyInput: "250 Volts (three-phase)",
    maximumOutputCurrent: "32 Amps",
    maximumOutputPower: "7.4 kW",
    evChargingLevels: "Level 2",
    primaryCountries: "China",
  },
  {
    evConnectorType: "GB/T (DC)",
    outputCurrentType: "DC (Direct Current)",
    supplyInput: "440 Volts",
    maximumOutputCurrent: "250 Amps",
    maximumOutputPower: "237.5 kW",
    evChargingLevels: "Level 3 (DC fast charging)",
    primaryCountries: "China",
  },
  {
    evConnectorType: "Tesla NACS",
    outputCurrentType: "AC/DC",
    supplyInput: "Single or three-phase",
    maximumOutputCurrent: "48 Amps (AC) 400 Amps (DC)",
    maximumOutputPower: "250 kW",
    evChargingLevels: "Level 2 / Level 3",
    primaryCountries: "USA, Canada",
  },
  {
    evConnectorType: "BEVC-DC0001",
    outputCurrentType: "DC (Direct Current)",
    evChargingLevels: "Level 3 (DC fast charging)",
    primaryCountries: "India",
  },
];
